apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hemant-daemonset
  namespace: hemant-ns
  labels:
    app: myapp
    component: daemonset
spec:
  selector:
    matchLabels:
      app: myapp
      component: daemon
  template:
    metadata:
      labels:
        app: myapp
        component: daemon
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80